<div class="register">
    <div class="container">
        <center><h1>Modificar</h1></center>

        <?php $currentUser = $this->user ?>
        <form method="post"
              action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'update')); ?>">
            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <label for="name">Nombre</label>
                        <input type="text" class="form-control" id="name" placeholder="Nombre" name="name"
                               value="<?php echo $this->escape($currentUser->getName()); ?>">
                    </div>
                    <div class="col-md-6">
                        <label for="lastName">Apellido</label>
                        <input type="text" class="form-control" id="lastName" placeholder="Apellido" name="lastName"
                               value="<?php echo $this->escape($currentUser->getLastName()); ?>">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="email">Correo</label>
                <input type="email" class="form-control" id="email" placeholder="Correo" name="email"
                       value="<?php echo $this->escape($currentUser->getEmail()); ?>">
            </div>

            <div class="form-group">
                <label for="password">Contraseña</label>
                <input type="text" class="form-control" id="password" placeholder="Password" name="password"
                       value="<?php echo $this->escape($currentUser->getPassword()); ?>">
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <?php $elementos = explode('-',$currentUser->getDateBirth());?>
                        <label for="password">Fecha de Nacimiento</label>
                        <div class="btn-group" role="group" aria-label="...">

                            <select type="text" class="btn btn-default" name="inputDay">
                                <option>Día</option>
                                <?php
                                for ($i = 1; $i <= 31; $i++) {
                                    if($elementos[2]==$i){
                                        echo "<option selected>$i</option>";
                                    }else {
                                        echo "<option>$i</option>";
                                    }
                                }
                                ?>
                            </select>

                            <select type="text" class="btn btn-default" name="inputMonth">
                                <?php
                                $months = array("Mes"=>0, "Enero"=>1, "Febrero"=>2, "Marzo"=>3, "Abril"=>4, "Mayo"=>5,
                                                "Junio"=>6, "Julio"=>7, "Agosto"=>8, "Septiembre"=>9, "Octubre"=>10,
                                                "Noviembre"=>11, "Diciembre"=>12);

                                foreach($months as $month => $noMonth){
                                    if($elementos[1]==$noMonth){
                                        echo "<option selected>$month</option>";
                                    }else {
                                        echo "<option>$month</option>";
                                    }
                                }
                                ?>
                            </select>

                            <select type="text" class="btn btn-default" name="inputYear">
                                <option>Año</option>
                                <?php
                                for ($i = 1980; $i <= 2010; $i++) {
                                    if($elementos[0]==$i){
                                        echo "<option selected>$i</option>";
                                    }else {
                                        echo "<option>$i</option>";
                                    }
                                }
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <label for="inputType">Tipo de Usuario</label>
                        <select type="text" class="btn btn-default" name="typeUser">
                            <?php if($currentUser->getTypeUser()->getId()==1){?>
                                <option value="1" selected>Administrador</option>
                                <option value="2">Cliente</option>
                            <?php }else{ ?>
                                <option value="1">Administrador</option>
                                <option value="2" selected>Cliente</option>
                            <?php } ?>
                        </select>
                    </div>

                </div>
            </div>

            <div class="form-group sex">
                <?php if($currentUser->getSex()=="Mujer"){?>
                    <label><input type="radio" name="sex" value="Hombre">Hombre</label>
                    <label><input type="radio" name="sex" value="Mujer" checked>Mujer</label>
                <?php }else{ ?>
                    <label><input type="radio" name="sex" value="Hombre" checked>Hombre</label>
                    <label><input type="radio" name="sex" value="Mujer">Mujer</label>
                <?php } ?>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-info addUser">Actualizar</button>
                <a href="<?php echo $this->url(array('module'=>'admin', 'controller' => 'user', 'action' => 'index'),null,true);?>" class="btn btn-default pull-right" style="margin-right: 10px;">Cancelar</a>
            </div>

            <input type="hidden" id="id" name="id" value="<?php echo $currentUser->getId();?>"/>
        </form>

    </div>
</div>