<div class="users">
    <div class="container">

        <div class="row">
            <div class="col-md-10">
                <h1 class="text-center">Usuarios</h1>
            </div>
            <div class="col-md-2">
                <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'new')); ?>"
                   class="btn btn-success pull-right">Nuevo Usuario</a>
            </div>
        </div>
        <br/>

        <div class="container">

            <table id='tableClientes' class="table table-striped">

                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Email</th>
                    <th>Password</th>
                    <th>Tipo de Usuario</th>
                    <th>Fecha de Nacimiento</th>
                    <th>Sexo</th>
                    <th>Opciones</th>
                </tr>

                <?php foreach ($this->entries as $entry): ?>
                    <tr>
                        <td class="idClient">
                            <?php echo $this->escape($entry->getId()); ?>
                        </td>
                        <td class="nameClient">
                            <?php echo $this->escape($entry->getName()); ?>
                        </td>
                        <td class="lastNameClient">
                            <?php echo $this->escape($entry->getLastName()); ?>
                        </td>
                        <td class="emailClient">
                            <?php echo $this->escape($entry->getEmail()); ?>
                        </td>
                        <td class="passwordClient">
                            <?php echo $this->escape($entry->getPassword()); ?>
                        </td>
                        <td class="typeUserClient">
                            <?php echo $this->escape($entry->getTypeUser()->getName()); ?>
                        </td>
                        <td class="dateBirthClient">
                            <?php echo $this->escape($entry->getDateBirth()); ?>
                        </td>
                        <td class="sexClient">
                            <?php echo $this->escape($entry->getSex()); ?>
                        </td>
                        <td>
                            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'edit', 'id' => $entry->getId())); ?>">
                                <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                            </a>&nbsp;
                            <a href="#"
                               onclick="confirmDeleteUser(<?php echo $entry->getId(); ?>,'<?php echo $entry->getName(); ?>');">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </a>
                        </td>
                    </tr>

                <?php endforeach ?>

            </table>

        </div>
    </div>
</div>

<br/>

<div id="dialog-delete" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Eliminar Usuario</h4>
            </div>
            <div class="modal-body">
                <p>¿Esta seguro que desea eliminar el usuario <b id="nameUser"></b>?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="deleteUser()" class="btn btn-primary">Aceptar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->