<div class="users">
    <div class="container">
        <center><h1>Usuarios</h1></center>
        <br/>
        <div class="container">

            <table id='tableClientes'>

                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Email</th>
                    <th>Password</th>
                    <th>Tipo de Usuario</th>
                    <th>Fecha de Nacimiento</th>
                    <th>Sexo</th>
                </tr>

                <?php foreach ($this->entries as $entry): ?>
                    <tr>
                        <form
                            action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'modify')); ?>"
                            method="post">
                            <td class="idClient">
                                <input type="number" class="form-control" name="id"
                                       value="<?php echo $this->escape($entry->getId()); ?>" readonly/>
                            </td>
                            <td class="nameClient">
                                <input type="text" class="form-control" name="name"
                                       value="<?php echo $this->escape($entry->getName()); ?>"/>
                            </td>
                            <td class="lastNameClient">
                                <input type="text" class="form-control" name="lastName"
                                       value="<?php echo $this->escape($entry->getLastName()); ?>"/>
                            </td>
                            <td class="emailClient">
                                <input type="email" class="form-control" name="email"
                                       value="<?php echo $this->escape($entry->getEmail()); ?>"/>
                            </td>
                            <td class="passwordClient">
                                <input type="text" class="form-control" name="password"
                                       value="<?php echo $this->escape($entry->getPassword()); ?>"/>
                            </td>
                            <td class="typeUserClient">
                                <input type="text" class="form-control" name="typeUserId"
                                       value="<?php echo $this->escape($entry->getTypeUserId()); ?>"/>
                            </td>
                            <td class="dateBirthClient">
                                <input type="date" class="form-control" name="dateBirth"
                                       value="<?php echo $this->escape($entry->getDateBirth()); ?>"/>
                            </td>
                            <td class="sexClient">
                                <select name="sex">
                                    <?php if (($entry->getSex()) === "Hombre") { ?>
                                        <option value="Hombre" selected>Hombre</option>
                                        <option value="Mujer">Mujer</option>
                                    <?php } else { ?>
                                        <option value="Hombre">Hombre</option>
                                        <option value="Mujer" selected>Mujer</option>
                                    <?php } ?>
                                </select>
                            </td>
                            <td>
                                <button type="submit" name="btnModify">
                                    <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                                </button>
                            </td>
                            <td>
                                <button type="submit" name="btnDelete">
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                </button>
                            </td>
                        </form>
                    </tr>
                <?php endforeach ?>

            </table>

        </div>
    </div>
</div>

<br/>