<div class="register">
    <div class="container">
        <center><h1>Modificar</h1></center>

        <form method="post"
              action="<?php echo $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'sign')); ?>">
            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <label for="name">Nombre</label>
                        <input type="text" class="form-control" id="name" placeholder="Nombre" name="name" value="<?php echo $this->escape($this->id); ?>">
                    </div>
                    <div class="col-md-6">
                        <label for="lastName">Apellido</label>
                        <input type="text" class="form-control" id="lastName" placeholder="Apellido" name="lastName">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="email">Correo</label>
                <input type="email" class="form-control" id="email" placeholder="Correo" name="email">
            </div>

            <div class="form-group">
                <label for="password">Contraseña</label>
                <input type="text" class="form-control" id="password" placeholder="Password" name="password">
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">

                        <label for="password">Fecha de Nacimiento</label>
                        <div class="btn-group" role="group" aria-label="...">

                            <select type="text" class="btn btn-default" name="inputDay">
                                <option>Día</option>
                                <?php
                                for ($i = 1; $i <= 31; $i++) {
                                    echo "<option>$i</option>";
                                }
                                ?>
                            </select>

                            <select type="text" class="btn btn-default" name="inputMonth">
                                <option>Mes</option>
                                <option>Enero</option>
                                <option>Febrero</option>
                                <option>Marzo</option>
                                <option>Abril</option>
                                <option>Mayo</option>
                                <option>Junio</option>
                                <option>Julio</option>
                                <option>Agosto</option>
                                <option>Septiembre</option>
                                <option>Octubre</option>
                                <option>Noviembre</option>
                                <option>Diciembre</option>
                            </select>

                            <select type="text" class="btn btn-default" name="inputYear">
                                <option>Año</option>
                                <?php
                                for ($i = 1980; $i <= 2010; $i++) {
                                    echo "<option>$i</option>";
                                }
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <label for="inputType">Tipo de Usuario</label>
                        <select type="text" class="btn btn-default" name="typeUserId">
                            <option value="1">Administrador</option>
                            <option value="2">Cliente</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group sex">
                <label><input type="radio" name="sex" value="Hombre">Hombre</label>
                <label><input type="radio" name="sex" value="Mujer">Mujer</label>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-info addUser">Enviar</button>
            </div>
        </form>

    </div>
</div>