<!DOCTYPE html>
<html>
<head>
    <title>Campion de MEXICO</title>
    <meta charset="UTF-8">

    <style>
        header {
            position: absolute;
        }
    </style>

</head>
<body>

<!--Start the carousel -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <div class="container">

        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">

            <div class="item active">
                <img src="http://tarotida.com/wp-content/imagenes/soldados.jpg" alt="Soldados 1">

                <div class="carousel-caption">
                </div>
            </div>

            <div class="item">
                <img src="http://www.fondos7.net/wallpaper-original/wallpapers/soldados-de-guerra-4918.jpg"
                     alt="Soldados 2">

                <div class="carousel-caption">
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<div class="about">
    <div class="container">
        <div class="row">

            <div class="col-md-6">
                <h1>CAMPION DE MÉXICO</h1>

                <p>Somos la empresa líder en la venta y servicio de vehiculos recreativos, marinos terrestres y todo
                    terreno en el sureste mexicano; contamos con las mejores marcas en cada categoría y con un equipo
                    humano de trabajo altamente calificado.</p>

                <p>Nuestra misión es ofrecer a nuestros clientes una amplia gama de vehiculos recreativos, marinos,
                    terrestres y todo terreno de alta calidad y desempeño, así como dar el soporte, servicio post-venta
                    y resguardo que permita mantenerlos en excelentes condiciones.</p>

                <p>Somos una empresa 100% yucateca, integrada por un grupo de trabajo especializado con años de
                    experiencia en el mercado; sólo aqui encontrará las mejores marcas y opciones que mejor se adapten a
                    sus necesidades, ya sea una moto acuática, una lancha, una vehiculo todo terreno p un vehiculo para
                    la ciudad, simplemente recuerde que... en Campio de México nuestra experiencia y servicio son su
                    mejor garantía.</p>
            </div>

            <div class="col-md-6">
                <video src="https://www.youtube.com/watch?v=MZoO8QVMxkk" controls></video>
            </div>

        </div>
    </div>
</div>

<div class="catalog">
    <div class="container">
        <h2>
            <center>CATÁLOGO</center>
        </h2>

        <div class="row">
            <div class="col-md-4">

                <div class="thumbnail">
                    <img src="http://depaseo.co/fotografias/extremo/lancha/lancha-1.jpg">
                </div>

                <div class="thumbnail">
                    <img src="http://www.solucionesi07.com/attachments/Image/motos_suzuki_010.jpg?1368670181960">
                </div>

            </div>

            <div class="col-md-4">

                <div class="thumbnail">
                    <img src="http://luhho.com/l/templates/siteground103/images/yamaha_fx_sho.jpg">
                </div>

                <div class="thumbnail">
                    <img src="http://www.remolqalia.com/catalog/images/multy-chassis.jpg">
                </div>

            </div>

            <div class="col-md-4">

                <div class="thumbnail">
                    <img src="http://imagenesdecarros.net/sites/default/files/4/jeep-todo-terreno_2.jpg">
                </div>

                <div class="thumbnail">
                    <img src="http://upload.wikimedia.org/wikipedia/commons/e/eb/Logo_hero3.jpeg">
                </div>

            </div>
        </div>
    </div>
</div>

<div class="pre-owned">
    <div class="container">
        <h2>
            <center>SEMINUEVOS</center>
        </h2>

        <div class="row">
            <div class="col-md-4">

                <div class="row">
                    <div class="col-md-8">
                        <div class="thumbnail">
                            <img src="http://depaseo.co/fotografias/extremo/lancha/lancha-1.jpg">
                        </div>
                    </div>

                    <div class="col-md-4">
                        <h6>Commander X</h6>
                        <h6>Mérida</h6>
                        <button type="button" class="btn btn-primary know-more">Conoce más</button>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8">
                        <div class="thumbnail">
                            <img
                                src="http://www.solucionesi07.com/attachments/Image/motos_suzuki_010.jpg?1368670181960">
                        </div>
                    </div>

                    <div class="col-md-4">
                        <h6>RXT 2010</h6>
                        <h6>Mérida</h6>
                        <button type="button" class="btn btn-primary know-more">Conoce más</button>
                    </div>
                </div>
            </div>

            <div class="col-md-4">

                <div class="row">
                    <div class="col-md-8">
                        <div class="thumbnail">
                            <img src="http://luhho.com/l/templates/siteground103/images/yamaha_fx_sho.jpg">
                        </div>
                    </div>

                    <div class="col-md-4">
                        <h6>RXT 255 iS</h6>
                        <h6>Cancún</h6>
                        <button type="button" class="btn btn-primary know-more">Conoce más</button>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8">
                        <div class="thumbnail">
                            <img src="http://www.remolqalia.com/catalog/images/multy-chassis.jpg">
                        </div>
                    </div>

                    <div class="col-md-4">
                        <h6>GTI 130</h6>
                        <h6>Cancún</h6>
                        <button type="button" class="btn btn-primary know-more">Conoce más</button>
                    </div>
                </div>

            </div>

            <div class="col-md-4">

                <div class="row">
                    <div class="col-md-8">
                        <div class="thumbnail">
                            <img src="http://imagenesdecarros.net/sites/default/files/4/jeep-todo-terreno_2.jpg">
                        </div>
                    </div>

                    <div class="col-md-4">
                        <h6>Commander LTD</h6>
                        <h6>Mérida</h6>
                        <button type="button" class="btn btn-primary know-more">Conoce más</button>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8">
                        <div class="thumbnail">
                            <img src="http://upload.wikimedia.org/wikipedia/commons/e/eb/Logo_hero3.jpeg">
                        </div>
                    </div>

                    <div class="col-md-4">
                        <h6>Maño 29.4 Center C.</h6>
                        <h6>Mérida</h6>
                        <button type="button" class="btn btn-primary know-more">Conoce más</button>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>

</body>
</html>