<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php
    $this->headLink()->appendStylesheet($this->baseUrl() . '/bootstrap-3.3.2-dist/bootstrap-3.3.2-dist/css/bootstrap.min.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/styles/login.css');

    $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-2.1.3.min.js');
    $this->headScript()->appendFile($this->baseUrl() . '/bootstrap-3.3.2-dist/bootstrap-3.3.2-dist/js/bootstrap.min.js');

    echo $this->headLink();
    echo $this->headScript();
    ?>
    <title>Campion México</title>
</head>
<body>
<div class="container">

    <form class="form-signin" action="<?php echo $this->url(array('module'=>'admin', 'controller' => 'login', 'action' => 'index'));?>" method="post">
        <h2 class="form-signin-heading">Ingresa</h2>
        <input type="text" class="input-block-level" id="userName" name="userName" placeholder="Nombre de usuario" required="">
        <input type="password" class="input-block-level" id="password" name="password" placeholder="Contraseña" required="">
        <label class="checkbox">
            <input type="checkbox" value="remember-me"> Recuérdame
        </label>
        <?php if ($this->message!=null):?>
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <?php echo $this->message;?>
            </div>
        <?php endif;?>
        <?php if ($this->error!=null):?>
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <?php echo $this->error;?>
            </div>
        <?php endif;?>
        <button class="btn btn-large btn-primary" type="submit">Ingresar</button>
    </form>

</div> <!-- /container -->
</body>
