<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Encabezado</title>

    <?php
    $this->headLink()->appendStylesheet($this->baseUrl() . '/bootstrap-3.3.2-dist/bootstrap-3.3.2-dist/css/bootstrap.min.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/styles/campion de mexico2.css');

    $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-2.1.3.min.js');
    $this->headScript()->appendFile($this->baseUrl() . '/bootstrap-3.3.2-dist/bootstrap-3.3.2-dist/js/bootstrap.min.js');
    $this->headScript()->appendFile($this->baseUrl() . '/js/campion de mexico.js');

    echo $this->headLink();
    echo $this->headScript();
    ?>

</head>
<body>

<!--Modal Conoce mas-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Informacion</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!--Modal LogIn-->
<div class="modal fade" id="modalLogIn" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Log In</h4>
            </div>
            <div class="modal-body">
                <form method="post"
                      action="<?php echo $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'login')); ?>">
                    <div class="form-group">
                        <label for="inputEmail">Correo</label>
                        <input type="email" class="form-control" id="inputEmail" placeholder="Correo" name="inputEmail">
                    </div>

                    <div class="form-group">
                        <label for="inputPassword">Contraseña</label>
                        <input type="password" class="form-control" id="inputPassword" placeholder="Contraseña"
                               name="inputPassword">
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-info">Entrar</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <form
                    action="<?php echo $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'register')); ?>">
                    <input type="submit" class="btn btn-info" value="Registrate">
                </form>
            </div>
        </div>
    </div>
</div>

<header>
    <div class="container">
        <div class="row">

            <div class="col-md-2">
                <div class="logo">
                    <div class="container">
                        <img
                            src="http://a1011.phobos.apple.com/us/r30/Purple/v4/18/b9/e2/18b9e206-5e3e-7ad6-9344-79230bbebbc1/mzl.qqymexrn.png">
                        <h4>Campion</h4>
                        <h4>de Mexico</h4>
                    </div>
                </div>
            </div>

            <div class="col-md-10">

                <div class="socials">
                    <a href="https://www.facebook.com/"><img
                            src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xfp1/v/t1.0-1/p160x160/1377580_10152203108461729_809245696_n.png?oh=5b4038c5a0314c00dad244e12329039e&oe=5525B87D&__gda__=1432708360_0e304448c6eff5add8aebca77d04176d"></a>
                    <a href="https://twitter.com/?lang=es"><img
                            src="http://www.ukdigitalmedia.company/images/twitter.png"></a>
                    <a href="https://www.youtube.com/"><img
                            src="http://bodhisattvamusic.com/wp-content/uploads/2014/03/youtube-circle.png"></a>
                    <a href="https://plus.google.com/"><img
                            src="http://img3.wikia.nocookie.net/__cb20150104105518/markiplier/images/7/7e/Google%2B_Icon.png"></a>
                </div>

                <div class="telephones">
                    <ul class="pull-right">
                        <li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>Mérida 01 (999)
                            911 0784
                        </li>
                        <li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>Cancún 01 (998)
                            889 9723
                        </li>
                        <li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>Campeche 01
                            (981) 127 1699
                        </li>
                    </ul>
                </div>

                <div class="nav">
                    <ul class="pull-right">
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index')); ?>">Inicio</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'enterprise')); ?>">Empresa</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'catalog')); ?>">Catálogo</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'services')); ?>">Servicios</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'user', 'action' => 'index')); ?>">Clientes</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'videos')); ?>">Videos</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'seminew')); ?>">Semi-Nuevos</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'events')); ?>">Eventos</a>
                        </li>
                        <li class="logIn"><a href="#modalLogIn">Log In</a></li>
                        <li>
                            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'contact')); ?>">Contacto</a>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
</header>

<?php echo $this->layout()->content ?>

<footer>
    <div class="row">
        <div class="col-md-8">
            <br/>
            <ul>
                <li>2015 Campion de Mexico S.A. DE C.V.</li>
                <li>KM 17 Carr. MERIDA-PROGRESO, Tablaje Catastral 16503 C.P. 97300 Mérida, Yucatán, México</li>
                <li>Tel. (01 999) 911.01.84 Copyright c 2015 www.campionmexico.com. Todos los derechos reservados.</li>
                <li>Aviso de Privacidad</li>
            </ul>
        </div>
        <div class="col-md-4">
        </div>
    </div>
</footer>

</body>
</html>